name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Caddy to proxy Prometheus
        run: |
          docker run -d --name promproxy -p 9090:9090 caddy caddy reverse-proxy --from :9090 --to https://${{ secrets.PROMETHEUS_REMOTE_WRITE_DESTINATION }} --change-host-header
      - name: Run Netdata
        uses: ./
        with:
          exporting-config: |
            [prometheus_remote_write:prom]
            enabled = yes
            destination = 127.0.0.1:9090
            username = ${{ secrets.PROMETHEUS_REMOTE_WRITE_USERNAME }}
            password = ${{ secrets.PROMETHEUS_REMOTE_WRITE_PASSWORD }}
            remote write URL path = /api/v1/write
            update every = 5

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Playwright and dependencies
        run: pnpx playwright install --with-deps
